### ISSUE TITLE
Question on walking a client

### ISSUE THREAD

**Issue by lebogan** [aca-labs/crystal-snmp#4]
Is it possible to do a v3 walk on a client. I saw the walk method and it works for v2c. I'm basically trying to replace the external snmpwalk utility in one of my apps.

Thanks for any insight.

- btw: awesome shard!

**Comment by stakach** [comment]
I've added basic support for V3 in the client
https://github.com/spider-gazelle/crystal-snmp/blob/master/src/snmp/client.cr#L19

I didn't actually write the client as we use the shard in a very different way so let me know how you travel and also happy to accept pull requests if there is anything that makes your life easier - I've yet to add helpers for parsing things like IP addresses or MAC addresses, mostly due to time constraints, for instance

Also haven't had any real world requirement for SNMPv3 as we mainly deal with traps.
So beyond testing against snmp labs and a cisco switch in our office I haven't done much with it - so happy to help with anything that improves it further :)

**Comment by lebogan** [comment]
Thank you for the update. I can now do:
```
  # Setup session
    session = SNMP::V3::Session.new(args[:user],
      args[:auth_pass],
      args[:priv_pass],
      auth_protocol: args[:auth], 
      priv_protocol: args[:priv])
    client = SNMP::Client.new(args[:host], session, 161)
    messages = client.walk(oid)
```
Once I figure out how to test for each message type, I can process the text in a meaningful way. 

Thanks again. I'm closing this.
